### ISSUE TITLE
[ Style ] Safari 환경 폰트 변경 이슈 및 홈 화면 푸터 바닥에 안 붙음

### ISSUE THREAD

**Issue by hyun907** [likelion-ssu/lion-s-study#147]
## 💡 Feature Issue
Safari 환경
- 폰트 적용 제대로 되지 않는 이슈
- 푸터 바닥에 붙지 않는 이슈

## 🌿  To-do
- [ ] SUIT 폰트 추가
- [ ] 프리텐다드로 변경할 부분 변경 (Top Bar)
- [ ] 로그인 구글 버튼 폰트 변경
- [ ] 푸터 해결

## 📚 ETC

<img width="969" alt="Image" src="https://github.com/user-attachments/assets/0a836d63-6cb8-46c0-9c17-3cda9e83a395" />

<img width="975" alt="Image" src="https://github.com/user-attachments/assets/948ec8d9-903b-4091-81aa-47bb8e6710eb" />

**Comment by hyun907** [comment]
간단한 CSS 작업이었기 때문에 git fork sync 문제 해결하면서 테스트용 커밋으로 메인에 바로 푸시했습니다.
폰트 깨진 이슈는 폰트 추가로 해결했습니다. global.css에 다음과 같이 font-family 정의해두었습니다.
```css
@font-face {
  font-family: "SUIT Variable";
  src: url("/fonts/SUITVariable.woff2") format("woff2");
  font-weight: 45 920;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: "Roboto-Medium";
  src: url("/fonts/Roboto-Medium.woff2") format("woff2");
  font-weight: 500;
  font-style: normal;
  font-display: swap;
}
```

푸터가 바닥에 안 붙는 이슈는 `layout.tsx`에서 Analytics 태그 뒤에 불필요한 `;` 세미콜론이 텍스트 1줄을 만들어 렌더링해서 1줄 만큼 높이가 떠있는 현상이었습니다.
