### ISSUE TITLE
[ Feat ] PlusBtn 컴포넌트화

### ISSUE THREAD

**Issue by hyun907** [likelion-ssu/lion-s-study#18]
## 💡 Feature Issue
재사용되는 버튼 컴포넌트 생성

## 🌿  To-do
- [x] 컴포넌트 props에 따른 동적 디자인 퍼블리싱

### 피그마 화면
<img width="291" alt="Image" src="https://github.com/user-attachments/assets/4e4b86e0-e126-479b-85f5-5925584e2ae5" />

## 사용법
1. _component/common/PlusBtn을 불러오기
2. 해당 컴포넌트는 다음과 같은 props를 받음
```
interface BtnProps {
  text: string;
  state?: "default" | "active";
}
```
- text에 버튼에 들어갈 텍스트 작성
- state에 회색 버튼이면 default를, 흰색 버튼이면 active를 넣어주기
3. 해당 컴포넌트 쓰는 곳에 커스텀 레이아웃을 쓰려면 btnWrapper로 자유롭게 묶고 속성 적용하기

### 실제 적용 결과
```tsx
export default function Test() {
  const handleClick = () => {
    console.log("click Event");
  };

  return (
    <div>
      <PlusBtn text="생성하기" />

      <div className={styles.btnWrapper1} onClick={handleClick}>
        <PlusBtn text="생성하기" />
      </div>

      <div className={styles.btnWrapper2} onClick={handleClick}>
        <PlusBtn text="생성하기" state="active" />
      </div>

      <div className={styles.btnWrapper3}>
        <span onClick={handleClick}>
          <PlusBtn text="이어서 작성하기" />
        </span>
        <span onClick={handleClick}>
          <PlusBtn text="작성 중단하기" state="active" />
        </span>
      </div>
    </div>
  );
}
```

```css
.btnWrapper1 {
  display: flex;
}

.btnWrapper2 {
  display: flex;
  justify-content: flex-end;
}

.btnWrapper3 {
  display: flex;
  justify-content: center;
  gap: 2rem;
}
```

실제 렌더링 결과

![Image](https://github.com/user-attachments/assets/ffade4a9-2a55-4053-8a20-a72893336949)

### ETC
참고로 서버 컴포넌트 → 클라이언트 컴포넌트로 함수(onClick)를 넘기는 것은 불가능합니다!
